services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "SqlServer2022!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver

volumes:
  mssqldata:
